### ISSUE TITLE
Create a object blog page template

### ISSUE THREAD

**Issue by TeamXerbutri** [TeamXerbutri/teamxerbutri.github.io#2]
Create the template for the object page containing the blog

**Comment by HelmerDenDekker** [comment]
So I was thinking; At this moment:
- we have a data structure for the back-end.
- The structure is persisted in DB
- The structure is parsed to editable pages in CMS (read-write-update)
- It is parsed to pages (maps, index, adventure) in website

What are we doing at the moment:
- We are translating the website backend and data structure into JavaScript.

Running into problems with having a data structure in the frontend and what to do with all these templates which are usefull etc.

helmerdendekker.github.io is a fine example. We just have text and pictures to display on this site, it should not be this hard, difficult or heavy.

The datastructure was introduced for the CMS part. Why don't we keep it for CMS-purposes, and from that CMS/datastructure create the pages we need.

Because for the website it is quite simple:

**Tile-page with all of the visited sites:** This is plain html, with a filter function in js, and lazy loading for the pictures.
**Maps** This only has openLayers
**Adventure** This only has photoswipe
**AdventureWithMaps** Has the extended photoswipe with openlayers.

From a performance point of view, a multi-page application with routing is the best.
A single page application is simpler from a framework point of view, but why do what the browser does best?

All things considered (backward compatibility etc) I think we best marry SPA and MPA to get a three-page application, which complicates stuff.

My proposal:
- Generate as much html as possible from the datastructure
- Load this html with javascript into the website.
- Create an app to generate the html with the existing datasctructure. (Move PHP into a C# app instead of JS)

**Comment by HelmerDenDekker** [comment]
Next problem at hand:
- How to route with javascript (using vite) to a multiple nested pages?

**Comment by HelmerDenDekker** [comment]
Whaaa. This is complicated:
![XerbutriRoutes](https://github.com/TeamXerbutri/teamxerbutri.github.io/assets/61043118/c368b205-b570-49eb-9c10-83c50837fbb5)

There are three main templates:
- Home
- Maps
- Blog

Blog has a blog-category and dependent on the blog (abbrev) can be written in several languages

Depending on the blog type (category) and/or the availability the blog can have photoswipe OR photoswipe-extended-with-openlayers

**Comment by HelmerDenDekker** [comment]
Running into a problem with adding html into a vite rendered page

**Comment by HelmerDenDekker** [comment]
Okay!
Newest thoughts on this subject:
- There are thee pages I can name, so this IS a multi-page application. Not a SPA. In the future it would be nice if I could turn this into a MPA instead. We'll see. For now I need something that works
- Loading the html with vite is a pain in the @$$. ALSO, there are "universal truths" that will be duplicated this way, and I do not like that

**Comment by HelmerDenDekker** [comment]
The routing system works. 
I wanted to do a quick try with markdown transformations, because it is a nice standard for my blogs.
However, this does not go fluently.

Put this on hold because we need a good solution for this problem.
IF I a going the markdown-javascript way it will be very javascript heavy.
I really do not know how to make the vite-html transform thing work. There are downsides to it as well

**Comment by TeamXerbutri** [comment]
Approved all recent changes. 
Official "Go" for next phase: Finish the index page
